### ISSUE TITLE
Results json not published

### ISSUE THREAD

**Issue by Kunaldargan** [wenxi-yue/SurgicalSAM#10]
Dear Authors,

Thank you for providing the code. Can you also publish the result JSON files generated from the best checkpoint model?
This is essential to recreate the experiments and validate the results.

Regards

**Comment by wenxi-yue** [comment]
Hi,

Thanks for your interest in our work. Sorry for the late reply. 

Our results should be reproducible by running inference.py using the provided checkpoints. Could you please specify which JSON file is needed?

**Comment by wenxi-yue** [comment]
Hi,

I have just noticed that the previous checkpoint link has expired. I have updated the link, so you can now use the provided checkpoints to reproduce the results by running Inference.py. Thank you!

**Comment by Kunaldargan** [comment]
Hello @wenxi-yue ,
Thank you for your reply. Can you please provide the results used to evaluate the model?
Typically in the COCO JSON format. 
Or if you can provide output masks which were used to calculate mcIOU and mIOU that will be equally helpful.

Regards

**Comment by wenxi-yue** [comment]
Hi, 

We did not use the COCO JSON format for evaluation due to the specialised evaluation metrics of the EndoVis datasets. Instead, we read the predicted and ground-truth masks and calculated their IoUs using the evaluation code provided by previous works (without employing the COCO JSON format). 

To obtain our output masks, you may run `inference.py` at [here](https://github.com/wenxi-yue/SurgicalSAM/tree/main#inference), and simply print `endovis_masks` [here](https://github.com/wenxi-yue/SurgicalSAM/blob/d58a8165872a9c51b789a707571f788d25aafa26/surgicalSAM/inference.py#L106). `endovis_masks` is a dictionary that stores all our output masks. And you may generate the COCO JSON files from these masks. 

Hope this helps.

**Comment by Kunaldargan** [comment]
Closing the issue,
Thank you for your time @wenxi-yue
